apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: compliance-operator
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/Surote/ocp-operation.git
    targetRevision: main
    path: modules/04-gitops-deploy-operators/manifests
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
