apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  labels:
    # the label is used to identify the machine config pool for the infra-logmon role for kubeletconfig
    machineconfiguration.openshift.io/role: infra-logmon
  name: infra-logmon
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,infra-logmon]}
  maxUnavailable: null
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/infra-logmon: ""
  paused: false