apiVersion: v1
kind: Namespace
metadata:
  name: 08-module
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-quota
  namespace: 08-module
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: example-limits
  namespace: 08-module
spec:
  limits:
  - type: Container
    default:
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    min:
      cpu: 50m
      memory: 64Mi
    max:
      cpu: "4"
      memory: 8Gi