apiVersion: v1
kind: Namespace
metadata:
  name: 02-module
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timecheck-deployment
  namespace: 02-module
  labels:
    app: timecheck
spec:
  replicas: 3
  selector:
    matchLabels:
      app: timecheck
  template:
    metadata:
      labels:
        app: timecheck
    spec:
      nodeSelector:
        node-role.kubernetes.io/infra-general: ""
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Equal
          value: reserved
          effect: NoSchedule
      containers:
        - name: timecheck-fastapi
          image: quay.io/rh_ee_swongpai/fast-localtime-check:lw-217d4d6d9b0e7886ae03b053db2c4f4cd8b104ec
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: timecheck-service
  namespace: 02-module
  labels:
    app: timecheck
spec:
  selector:
    app: timecheck
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: timecheck-route
  namespace: 02-module
  labels:
    app: timecheck
    type: sharded
spec:
  to:
    kind: Service
    name: timecheck-service
  port:
    targetPort: 8000
  tls:
    termination: edge