timeout: 30m
strictNodeScan: true
autoApplyRemediations: false
metadata:
  name: rs-on-workers
  namespace: openshift-compliance
  annotations:
    argocd.argoproj.io/sync-wave: "2"
debug: true
kind: ScanSetting
showNotApplicable: false
rawResultStorage:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  pvAccessModes:
    - ReadWriteOnce
  rotation: 3
  size: 1Gi
schedule: 0 17 * * *
suspend: false
# the roles need to be updated to the roles in the cluster
roles:
  - infra
  - worker
apiVersion: compliance.openshift.io/v1alpha1
maxRetryOnTimeout: 3
scanTolerations:
  - operator: Exists